# Generated by Django 5.1.3 on 2024-12-30 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('jornada', models.IntegerField(verbose_name='jornada laboral')),
                ('usuario', models.CharField(max_length=20)),
                ('ingreso', models.DateField()),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona_app.persona', verbose_name='persona')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'db_table': 'empleado',
                'managed': True,
            },
        ),
    ]
