# Generated by Django 5.1.3 on 2025-01-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50)),
                ('tercer_nombre', models.CharField(blank=True, max_length=50)),
                ('apellido_paterno', models.CharField(max_length=70)),
                ('apellido_materno', models.CharField(blank=True, max_length=70)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'db_table': 'persona',
            },
        ),
    ]
